server:
  port: 8765
spring:
  application:
    name: database-service
  profiles:
    active: dev


mybatis:
    type-aliases-package: com.pingan.fi.database.dao
    mapper-locations: mapper/**Mapper.xml

---
spring:
  profiles: dev
eureka:
  client:
      serviceUrl:
         defaultZone:  http://localhost:8761/eureka/
         register-with-eureka: false
         fetch-registry: false
datasource:
    jdbc-url: jdbc:mysql://localhost:3306/fi_db
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
