server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
zuul:
  ignoredServices: '*'
  routes:
    algorithm-service: /face/**
    database-service: /db/**
    users:
      path: /feature/fetch/**
      serviceId: database-service

---
spring:
  profiles: dev
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/