eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone:  http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
server:
  port: 8080
spring:
  application:
    name: gateway
