eureka:
  client:
    serviceUrl:
      defaultZone:  http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
server:
  port: 8764
spring:
  application:
    name: kettle-service
  profiles:
    active: dev

---
spring:
  profiles: dev
kettle:
  cluster:
    username: cluster
    password: cluster
    host: 192.168.40.235
    port: 8080
    name: cluster
    basePort: 40000
    socketsBufferSize: 2000
    socketsFlushInterval: 5000
    sockets_compressed: true
    slaveServersName: clusterMaster
  repository-path: Z://

---
spring:
  profiles: prod
kettle:
  cluster:
    username: cluster
    password: cluster
    host: 192.168.40.235
    port: 8080
  repository-path: Z://