server:
  port: 8080
spring:
  application:
    name: algorithm-service
  profiles:
    active: dev
---
#dev config
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
server:
  fi:
    uriPrefix: /bioauth/faceService
    hostname: 10.180.121.141:8080
  image:
    username: test
    password:  test
    hostname:  localhost:8788
logging:
  file: algorithm-service-out.log
  path: ./logs/
datasource:
    jdbc-url: jdbc:mysql://localhost:3306/fi_db
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: mapper/**Mapper.xml
---
#prod config
spring:
  profiles: prod
serverInfo:
  fi:
    uriPrefix: /bioauth/faceService
    host: 10.180.121.141
    port: 8080
    version: 1.0.0
    vendorName: Pingan
eureka:
  client:
    serviceUrl:
      defaultZone:  http://peer.registry.com:8761/eureka/,http://peer.registry.com:8762/eureka/,http://peer.registry.com:8763/eureka/