server:
  port: 8080
spring:
  profiles:
    active: dev
logging:
  file: algorithm-service-out.log

mybatis:
  mapper-locations: mapper/**Mapper.xml
---
#dev config
spring:
  profiles: dev
server:
  fi:
    uriPrefixFor1V1: /bioauth/faceService
    hostnameFor1V1: 190.192.7.74:8080
    uriPrefixFor1VN: /faceService
    hostnameFor1VN: 10.180.121.141:8080
  image:
    username: test
    password: test
    hostname: 190.192.1.225
---
spring:
  profiles: suzhou
server:
  fi:
    uriPrefix: /bioauth/faceService
    hostname: 10.180.121.141:8080
  image:
    username: test
    password:  test
    hostname:  localhost:8788
datasource:
    jdbc-url: jdbc:postgresql://172.21.140.111:25308/pakj_db
    username: pakj_user
    password: Huawei12#$
    driver-class-name: org.postgresql.Driver
